### ISSUE TITLE
Permission error in bin/run

### ISSUE THREAD

**Issue by cassaram09** [learn-co-curriculum/dynamic-orm-inheritance#13]
**Track:** Full Stack Web Development

**Issue Summary:** Student was having an issue with `bin/run`. I was expecting the code to output:

`song name: Hello`
`song album: 25`
`{"id"=>1, "name"=>"Hello", "album"=>"25", 0=>1, 1=>"Hello", 2=>"25"} `

but instead got:

`-bash: bin/run: Permission denied`

**Files:** `bin/run`

**Branch:** `master`

**Issue Details**

`$ bin/run`
`-bash: bin/run: Permission denied`

The permissions for this file seem to be configured incorrectly:

`$ cd bin`
`$ ls -l`
`-rw-r--r--  1 mattcassara  staff  341 Nov 13 12:41 run`

Also, the environment was not declared in `run`, which appeared to be contributing to the error as well:

`#!/usr/bin/env ruby`

Adjusting the permissions and adding that line of code seemed to fix this:

`$ chmod 750 bin/run`
`$ bin/run`
`song name: Hello`
`song album: 25`
`{"id"=>1, "name"=>"Hello", "album"=>"25", 0=>1, 1=>"Hello", 2=>"25"}`

@aturkewi

**Comment by aturkewi** [comment]
Thanks @cassaram09 
Fixed with PR #14 

For what it's worth, I ended up doing `chmod +x bin/run`. Check this out: https://www.tutorialspoint.com/unix/unix-file-permission.htm

The third number in `750` that you set would be mean that everyone (besides the owner and group to which the file belongs) would have _no_ permissions on the file. I think in this case, it just makes sense to give _everyone_ executable access rather than add executable to group and revoke read from everyone else. 

Thanks for raising this and giving a very detailed description! Very very helpful.
