### ISSUE TITLE
Spec file is missing.  Cannot complete lab.

### ISSUE THREAD

**Issue by m-gamao** [learn-co-curriculum/dynamic-orm-inheritance#27]
There is no spec file for this

**Comment by maxwellbenton** [comment]
Hi @guerilla17,

This lesson is a code-along and does not include tests. To register completion in learn, fork the lesson, make a change to the lesson, then run `learn submit`.

I am going to close this issue as this is the expected behavior of this lesson, but Learn is expecting you to submit tests to register completion of this lesson, please reopen this ticket.
